          :: [Put what you want here]
:: _______________________________________________


@echo off&(if defined @lo@ goto ¡)&setlocal disableDelayedExpansion&for /f "delims=: tokens=2" %%A in ('chcp') do set "@chcp@=chcp %%A>nul"&chcp 708>nul&set ^"@args@=%*"
set "@lo@= !#$&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~""
set "@hi@=¡¢¤¥§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ£"
(setlocal enableDelayedExpansion&for /l %%N in (0 1 93) do set "!@hi@:~%%N,1!=!@lo@:~%%N,1!")&cmd /c ^""%~f0" !@args@!"
%@chcp@%&exit /b
:¡
%Á%%Obfuscation_Name%%Edit_here%%æ%%Obfuscation_Name%%Edit_here%%ä%%Obfuscation_Name%%Edit_here%%é%%Obfuscation_Name%%Edit_here%%ð%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%ð%%Obfuscation_Name%%Edit_here%%ç%%Obfuscation_Name%%Edit_here%%ç%%Obfuscation_Name%%Edit_here%
%ä%%Obfuscation_Name%%Edit_here%%ð%%Obfuscation_Name%%Edit_here%%í%%Obfuscation_Name%%Edit_here%%ð%%Obfuscation_Name%%Edit_here%%ó%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%³%%Obfuscation_Name%%Edit_here%
%æ%%Obfuscation_Name%%Edit_here%%ä%%Obfuscation_Name%%Edit_here%%é%%Obfuscation_Name%%Edit_here%%ð%%Obfuscation_Name%%Edit_here%%¯%%Obfuscation_Name%%Edit_here%
%æ%%Obfuscation_Name%%Edit_here%%ä%%Obfuscation_Name%%Edit_here%%é%%Obfuscation_Name%%Edit_here%%ð%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%É%%Obfuscation_Name%%Edit_here%%ê%%Obfuscation_Name%%Edit_here%
%æ%%Obfuscation_Name%%Edit_here%%ä%%Obfuscation_Name%%Edit_here%%é%%Obfuscation_Name%%Edit_here%%ð%%Obfuscation_Name%%Edit_here%%¯%%Obfuscation_Name%%Edit_here%
%ñ%%Obfuscation_Name%%Edit_here%%â%%Obfuscation_Name%%Edit_here%%ö%%Obfuscation_Name%%Edit_here%%ô%%Obfuscation_Name%%Edit_here%%æ%%Obfuscation_Name%%Edit_here%

%ä%%Obfuscation_Name%%Edit_here%%í%%Obfuscation_Name%%Edit_here%%ô%%Obfuscation_Name%%Edit_here%
%æ%%Obfuscation_Name%%Edit_here%%ä%%Obfuscation_Name%%Edit_here%%é%%Obfuscation_Name%%Edit_here%%ð%%Obfuscation_Name%%Edit_here%%¯%%Obfuscation_Name%%Edit_here%
%æ%%Obfuscation_Name%%Edit_here%%ä%%Obfuscation_Name%%Edit_here%%é%%Obfuscation_Name%%Edit_here%%ð%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%õ%%Obfuscation_Name%%Edit_here%%é%%Obfuscation_Name%%Edit_here%%ê%%Obfuscation_Name%%Edit_here%%ô%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%ê%%Obfuscation_Name%%Edit_here%%ô%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%â%%Obfuscation_Name%%Edit_here%%ï%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%ð%%Obfuscation_Name%%Edit_here%%ã%%Obfuscation_Name%%Edit_here%%ç%%Obfuscation_Name%%Edit_here%%ö%%Obfuscation_Name%%Edit_here%%ô%%Obfuscation_Name%%Edit_here%%ä%%Obfuscation_Name%%Edit_here%%â%%Obfuscation_Name%%Edit_here%%õ%%Obfuscation_Name%%Edit_here%%ê%%Obfuscation_Name%%Edit_here%%ð%%Obfuscation_Name%%Edit_here%%ï%%Obfuscation_Name%%Edit_here%
%æ%%Obfuscation_Name%%Edit_here%%ä%%Obfuscation_Name%%Edit_here%%é%%Obfuscation_Name%%Edit_here%%ð%%Obfuscation_Name%%Edit_here%%¯%%Obfuscation_Name%%Edit_here%
%ñ%%Obfuscation_Name%%Edit_here%%â%%Obfuscation_Name%%Edit_here%%ö%%Obfuscation_Name%%Edit_here%%ô%%Obfuscation_Name%%Edit_here%%æ%%Obfuscation_Name%%Edit_here%

%ä%%Obfuscation_Name%%Edit_here%%í%%Obfuscation_Name%%Edit_here%%ô%%Obfuscation_Name%%Edit_here%
%æ%%Obfuscation_Name%%Edit_here%%ä%%Obfuscation_Name%%Edit_here%%é%%Obfuscation_Name%%Edit_here%%ð%%Obfuscation_Name%%Edit_here%%¯%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%
%æ%%Obfuscation_Name%%Edit_here%%ä%%Obfuscation_Name%%Edit_here%%é%%Obfuscation_Name%%Edit_here%%ð%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%
%æ%%Obfuscation_Name%%Edit_here%%ä%%Obfuscation_Name%%Edit_here%%é%%Obfuscation_Name%%Edit_here%%ð%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%©%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%ª%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%©%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%ª%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%©%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%ª%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%
%æ%%Obfuscation_Name%%Edit_here%%ä%%Obfuscation_Name%%Edit_here%%é%%Obfuscation_Name%%Edit_here%%ð%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%©%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%ª%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%©%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%ª%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%©%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%ª%%Obfuscation_Name%%Edit_here%%©%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%ª%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%
%æ%%Obfuscation_Name%%Edit_here%%ä%%Obfuscation_Name%%Edit_here%%é%%Obfuscation_Name%%Edit_here%%ð%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%©%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%ª%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%©%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%ª%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%©%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%ª%%Obfuscation_Name%%Edit_here%%©%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%ª%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%
%æ%%Obfuscation_Name%%Edit_here%%ä%%Obfuscation_Name%%Edit_here%%é%%Obfuscation_Name%%Edit_here%%ð%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%©%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%ª%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%©%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%ª%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%©%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%ª%%Obfuscation_Name%%Edit_here%%©%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%ª%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%
%æ%%Obfuscation_Name%%Edit_here%%ä%%Obfuscation_Name%%Edit_here%%é%%Obfuscation_Name%%Edit_here%%ð%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%©%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%ª%%Obfuscation_Name%%Edit_here%%©%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%ª%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%©%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%à%%Obfuscation_Name%%Edit_here%%ª%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%
%æ%%Obfuscation_Name%%Edit_here%%ä%%Obfuscation_Name%%Edit_here%%é%%Obfuscation_Name%%Edit_here%%ð%%Obfuscation_Name%%Edit_here%%¯%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%%¡%%Obfuscation_Name%%Edit_here%
%ñ%%Obfuscation_Name%%Edit_here%%â%%Obfuscation_Name%%Edit_here%%ö%%Obfuscation_Name%%Edit_here%%ô%%Obfuscation_Name%%Edit_here%%æ%%Obfuscation_Name%%Edit_here%
